apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: gamma
spec:
  storageClassName: gamma
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi