apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-gamma
spec:
  storageClassName: gamma
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/mysql/gamma"